apiVersion: v1
data:
  JWT_SECRET: c3VwZXJzZWNyZXRrZXktY2hhbmdlLW1l
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: backend:/Secret:default/backend-jwt-secret
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"JWT_SECRET":"c3VwZXJzZWNyZXRrZXktY2hhbmdlLW1l"},"kind":"Secret","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"backend:/Secret:default/backend-jwt-secret"},"name":"backend-jwt-secret","namespace":"default"}}
  creationTimestamp: "2026-03-17T10:42:30Z"
  name: backend-jwt-secret
  
  resourceVersion: "244484"
  uid: bd99867f-35c3-4f30-9cb5-b7449c3bb477
type: Opaque
