---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-jwt-secret
  namespace: default
spec:
  encryptedData:
    JWT_SECRET: AgAYexuiOigY4sXP6uUsO7+KectnU8uTc7ikeJkFO3JTDbMtBUoe7CzAw8mkYJ3ZvCoK0BHArAB8RyjnWs8R21yDZh0YooQ7/RYOgroDVVzTTr4Jk4tyISpQhB7XE4b7cCe0ltDQPsDRv6OXqNPGQPaCDXsdLbDH/9wgSm07aEWgFYriNG+W6uumMeO+g7qvsoK9IEl3qmcZy0Py4cYAnKYoyB7PKiiELD3leImJ/m11vtaCKCetdzwHcut1yIAvUmwjjkSy3ekWfIz/ZloPFtPJXai5uHuL0sf8dRFL7wjVkljdQRP+WRSc1aJoLeETOadHy9t9NVsNRBdltNlREzAA5fUfLFLA2IDyAWgL/fu7Jsyo0IpTSR6/5crnoAdXDDyZ2uQ6HEKb+7/Ixii694Jhz8VhWrCBb7M3aA5U7nQBoCWE0A8QBDEHMK8WD8P7YZRAbiAD7QiMPYAT+ctt20ijI2sQUv92XvfkCqfCf5z7X5srRjZRxLHGM7WkFpyikCU3A7R/iZtPTpzpAOkgqwwxRRIdrsqGsmSCq5XR7gj38DATUGnYdTE2OeOW5iW2/UekNpboR2bSf/kWPblkYU21MUosQLuUbGXJQwU4ezd9Tw+Z+u5YvJS45LzidHc/DDBa5k+R4S9gT71X8w9dvqxPydT6smTGC+/SYoVV4OodM5zjVFvI2ceM/VhfFcB24pASj0KrOSqslKXym9GWwjTYys6sD2PbgdcA8bTdxNEB+w/HL1gKEP6f6JS2jQ==
  template:
    metadata:
      creationTimestamp: null
      name: backend-jwt-secret
      namespace: default
