apiVersion: v1
data:
  DB_HOST: postgres-service
  DB_NAME: wellness
  DB_PORT: "5432"
  NODE_ENV: production
  PORT: "3000"
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: backend:/ConfigMap:default/backend-config
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"DB_HOST":"postgres-service","DB_NAME":"wellness","DB_PORT":"5432","NODE_ENV":"production","PORT":"3000"},"kind":"ConfigMap","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"backend:/ConfigMap:default/backend-config"},"name":"backend-config","namespace":"default"}}
  creationTimestamp: "2026-03-17T10:42:30Z"
  name: backend-config
  namespace: dev
  resourceVersion: "244485"
  uid: 525a82d7-c294-4a7e-8109-bc1203f4d7f3
