apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-deployment.yml
  - backend-service.yml
  - backend-config.yml
  - backend-secret.yml
  - backend-jwt-sealedsecret.yml
  - backend-jwt-sealedsecret-dev.yml
  
    
