apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-canary
  namespace: canary-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      track: canary
  template:
    metadata:
      labels:
        app: backend
        track: canary
    spec:
      containers:
        - name: backend
          image: ghcr.io/luisrodvilladaorg/wellness-ops-backend:v1.0.4 # new version
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
            - secretRef:
                name: backend-jwt-secret
