---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-jwt-secret
  namespace: dev
spec:
  encryptedData:
    JWT_SECRET: AgAA4ika6oo1tYzuzo8ipCksiI48EtLDAeFciOZTyTGJwbmJPw/DfDUWFrAtHzFafcbRNWqeAky+ZCFWrkgd85N91MgKv1ckJYrN91q1+7FH4X09FR3Qm2GjFEOj6BRB/+Lyfu2tsTPkrClj8RZ3uyRrbGn+qc0xgMR0JRNScp4k0KIR7PFC+uIOr1H3Q9jzRJQ+8dvwruQTIxVckeTpDgJ2s6dpbKOiOD0gCev+HYVpguxHvwSydGEdWi+9HU4TaJgn5cQo422ifKT0K7q1yu0TKEFdHPWcvt51/6zgenz3YRnLE8gglhHtHKrG8C1wRdLyGPffSKKNiRTz6Sky7XHQ2NJQ7gEXB1qxphyLUK1lcijl8Hz0R81euOxOrCdmm4jtmhpBE+l3kgaeg+aOttQeil3UyWgbNCrZ+USOiQw7Z6FkaOWDS98tcWAqgXSM7Um333a00VRN6838McKUUhmn0MjScEKekN6DyGVZ0fvazudhQ1uKpTJboXUoae+kE02rxlj7ZZKsnQmdcK3GjJxmphkmN+bC5EC1/d4nzt+Cx+7keL6svDEdLuG7bMeL/panPyAsxF3CfCtajQM5hA65e7RwDX4eMjvXXHwKj36GXLQn8XSc144jCBslNY2vKoHK5Tl1PPjZWan0c2DP8KFDAdSKye8+MhF2LfQRqCHTNwBx1BU0Zws3StArauWQU9DzEeyWVcwe/u44AF7q0CkisU0=
  template:
    metadata:
      creationTimestamp: null
      name: backend-jwt-secret
      namespace: dev
