---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-jwt-secret
  namespace: dev
spec:
  encryptedData:
    JWT_SECRET: AgCesCVs4HV+E6B5XnCotoe4Kfqo8bdzz9YqHL3UZtTSvPMjbASp30an3XNWZ0TNus7uPYkDJF3X5LWILuq4IMatlw0/1egAXXdMiGOtDJuKgtpj6wv/72bGpWOMaaxKHUy7+EN/yImJG2jc4I/M6apDEoGKPFrBWCLfNYUkWV/18btkGf6AA1qhIBRvFAMpaMoRgY59CdG4bVcoSFFg/ULp4rE10sbxy+1eaWQqr+1XV7Wieg65yIwWNHdXUL6zvAg5ns8G5pWy8YOS/w+Mx0iBpenMEw16OIiIMYqSINDpKqs9kjap2Rp9e3s/G/nT2vKOLDmU+kxEeWTfusbb31ZAIjbJE6nfXdwEBJ8hfTmdH9Ey09Qb8p2zij83qrQCSLBW8nO0v1O5djRHDmfE3uin4mKqM0BugD9TfWfpxGSffdtZFFEW6ynAkN1gVJihn1T2zP6I4ZCvbptzQezpTIGn5/2ywbqiEpp8hv2S1x+RT2SC7MQvLIj1hmLRtKXvjCh1nGEOtpkj9CPsxI8hWg8okwsXe3gD9IHxxdq5XN5yVyfioewi9b8w3yQAV9kaE+YJk8Ls+6SBFnf1SwdkV4HF/czOMtAuLhNhjGyS7GJgdKu6fxgQut+lZ0/izPZLAyUKOKe+UsTMHgMjwpDTENh3hgiRvWu1GFisnrXtRf0CCz0Xr3QrJsl48/WVDOUpApOBrJoh5cwHDfHNeSwfoD403GuQj/GSWciZOlmilhp2HzrsR7QP3luqmTtYUQ==
  template:
    metadata:
      creationTimestamp: null
      name: backend-jwt-secret
      namespace: dev
