apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  template:
    spec:
      containers:
        - name: backend
          image: ghcr.io/luisrodvilladaorg/wellness-ops-backend:131638df0c1832d42d7d2c27d9e214b8e5de58d6
