apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  template:
    spec:
      containers:
        - name: backend
          image: ghcr.io/luisrodvilladaorg/wellness-ops-backend:8cc5fb7fc0a01d9019aa4e5f9e013c4b7bf3e40a
          