apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  template:
    spec:
      containers:
        - name: backend
          image: ghcr.io/luisrodvilladaorg/wellness-ops-backend:b6899299ba96816f255e40e9f01c7abb668552de
          replicas: 1