apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  template:
    spec:
      volumes:
        - name: shared-logs
          emptyDir: {}

      containers:
        - name: backend
          volumeMounts:
            - name: shared-logs
              mountPath: /var/log/backend

        - name: log-sidecar
          image: busybox
          command: ["sh", "-c", "tail -n+1 -F /var/log/backend/app.log"]
          volumeMounts:
            - name: shared-logs
              mountPath: /var/log/backend
