apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
        - name: frontend-deployment
          image: ghcr.io/luisrodvilladaorg/wellness-ops-frontend:e01108adc475d4453567196c91bee4fda5ac24ed