apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
        - name: frontend-deployment
          image: ghcr.io/luisrodvilladaorg/wellness-ops-frontend:caf277b55f8ca48d8e3382cdf218486e45c85dba