apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
        - name: frontend-deployment
          image: ghcr.io/luisrodvilladaorg/wellness-ops-frontend:15aaeff89af045ffebaa852e5f2267cb41ae5138