---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-jwt-secret
  namespace: prod
spec:
  encryptedData:
    JWT_SECRET: AgAoTM9SlBPC+HA3cvFuRBHGDy7IyMw49v9i4yU8X7LoLVRu2QMGVwYh2Q6FDaQmgB1vpeFo00tg6cm1DqK1L3QfuR9vhVZvxfh2ZpID0n8hW0PoPciveieeWBnXWEHQBkM7VLnXXQG5d6fVo5Xa0yrDiWrJrQ/xFHhcKlFFvXTLgkWbk9qqDJSdiviqXraynDd/jw86DYPKqaIKhNR2QlpCg0S9PpslpmBOEuJC4YvYk2/w8ECFfNMRHOklDYDyLAIU2DaaTb9nvAS11dxwzEfAKoUz/k+fgC2/7oriqmLfgxyg9irxziRHl6EYYKdHWEam6c1+A/Kv8JqEHUsEV+7nDMRwHQndzDbkN5xsK43eHym62JlQer8ADByKQblGvvcXzWS4Auyt5PGfsHV5Cih5+L0gaKcrQSK/rWo/sF1ZXv1l4wKTfA4e4eNeZRtEgOabW3//VZjNUlhTqUYk9IJ1GE+pTfCv+lGggD9iWKPxtW5SlGAjQBP1i39sTL+I1tn34H05bM4ZD9Dyv6iAlbnAIvs9zcP2gIiuLVwPtcSCGMaIJSrvV6+XiVN4FOOTkaZJY/du7MvJ6S/X1Tjmlekhz2ZJxEPb/UwVoSvGFmkeXx1rwYkGCm0SwPkXn02FQ3c3GYWa75KMzWTRav+enpHwNxG/XBJUoc1x65HLDSQio5XXr7uMMdRxYnEaxzMwpVYH3x4pCGie6R6oC7yIp7dPAWo=
  template:
    metadata:
      creationTimestamp: null
      name: backend-jwt-secret
      namespace: prod
