---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-jwt-secret
  namespace: prod
spec:
  encryptedData:
    JWT_SECRET: AgBWHHuPSL4fimJ5FHxNGEoPxQ262IxYZodshA853KQnnl1JP2FajHVPdINjFJC/Bhtv5A4qCTnEAAv3E5neSxl3/kHZs5FXCXFdVMN33+TCDwAgMk3thLRQfjvKvun7Iwg2+QZw03exfCozSrciQUNxhriGFH/CaocUn0S7VQ8juBngnLxkToVzQAH3hH/SDh2AG4oA/oOr1CGFB9hrrT1jy5FQzOhHLQ4K2NBeYKWCf50mk3Oq7H1t/YyQNfIXdt4IfynlNwGWV/pwUDQjlnDNni4VLBVxkQXVL8fnUq3J5DzqpHL3IKS7fc9l0PLimPhPW5I6D+S5M0rZhbnQ3+N2m6WDfur7qwip5EeGLYvMvrIC2P00F2gr0I3BiSW5a/myV5mY/rk/efbXgLV1DEvug9NS/CFmy4131LlVMbqSPmU+obF5sWlvdX3CiXdNAT2SyTU8hzGMYh343WxhWih0H+FNI5dkak6J/e4KVsssEYjZp0tghvXYGMFeltc+KJfOLiaGQ3Jg80utV4rMIlJ24v51SUH7AiZsvuY/mXS2zqUIzvcR0TAD4fnSwwCcDChOxSL/4ZBwRn+hngBZKbjVFEsoGUbwV/ychFAGxz2yZ4O9G+rsbjM+ahIukOdKQBdRC+P6iESbELNIUEpfcITn81CWQAuQF+4+I0eXwVSTkjTkAvUB/tS23TvuByvePi1YmB21r5rOSWg4yhWOIqVytqXsCSyD9LYDCEEyfweqnvqi8SHpORwHeD0/Bg==
  template:
    metadata:
      creationTimestamp: null
      name: backend-jwt-secret
      namespace: prod
