---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-jwt-secret
  namespace: staging
spec:
  encryptedData:
    JWT_SECRET: AgAPp0Rj8g/7xZjjW7oshN2vaNl8gi+KTqVye028Sz5L9lWbm/EaJbX2/cSLXmWbWcOyYDNiAFPhWcJWZVqkD2kJz/7+Dxwwj4Zack3qNNoRCQLVpgMoiojJFPXtBE/LXyzWtcfAKmEVDrdY6Utfy7GQWb6d4mcVvY/IcpwXMVTZJ1iy7vWAFYj8x7KwKiJt5FC7AGcxnpFcirqCw4Sa6AxZaejJiw++vH62PIyRt6PpSEo2f0Bdu7QwUFDIuDV467ZPf0AHpehueEJsIoD0W+rZ6OU7CjIK3QG3Sy+n14CofeikNug4Fui2Q4eVJNAQ9YhvymULALZyXRzWyyzRvoXYVA57R448UOxnt+XMOGMxOLu7k6CVzQikzLFneSZrScUNFX/OTSEQECI/UOT3ukv47qgkIZnUmUo9NeeiY5eS4t0EnmdEnynTrzq67ZjSbObSv81EMZQQ2lMz0SqIP5fQ97W0ge1YvOdrE7zzGYpfKJP6hwNcjOScZAfhdDXZ2/VkTagenDKMcuR3oz+62eqzk5kO7xA5ejVmEvBBUHKK5ECCSCV3zbstZfRlojk6IRIE4iOUGUHv7le69cEmQhGjupZz+v6XG9vAgj/YZhkVNAVqV92JPZl9YZdUHzPgjAbGvZdoSHO1tS+1pGsyjC9jBzL0sJjWyluz4dOJRFfssyVlmIfGFHPfpD8JzOLLhSnylGYGpWqJ+amX1Ukvct451gNoU3ZttxWx00wTOZYuslXN8pk3AOdpBbXdYg==
  template:
    metadata:
      creationTimestamp: null
      name: backend-jwt-secret
      namespace: staging
