apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  template:
    spec:
      containers:
        - name: backend
          image: ghcr.io/luisrodvilladaorg/wellness-ops-backend:a9b398f10fc8932bef82e8ebe173e72d0b97e00dafb893a8486c9e4661010223