---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: arc-github-secret
  namespace: arc-runners
spec:
  encryptedData:
    github_token: AgCYgc0lu4wfJNbU5vnX+AL+y4o9oQc94k61gBz5boVELAKAQFuGOmOR6fIy5X+xSsw3gjIGRH3DrUc6OiMozui2eu2Q6UQuJwD5xoZzimX9y1mPijwdYyuc/SXY/OOppm6JpoQOA9Onovob+/BjlZJgkXPVqZqGB4O4qfqAPLts/v/K9LdDwYlxoVgLk0zcmwiwhJlv+dDfWWk/L+h0A2/iCbvdDkqbJ9Y1bLrkQoBvKiE18smFPZRzMX+TIBOgkjE5xpV3E5KItR/Mc8JNURbiEsDXd6+qVeBDsmAxg4oUYSDaX/sTQgz1JbV6MwRvDRmQklcVI3GqeySjuj789sJRR077ng6YTLwEUzuWq2i9AvehLWus3etSRyp647w/o1fcYDoQa5YY4L4oYR780vG+h/lpCqmNTI4pTqURMlA7GLYzUSAikcBpH1Td7SHYC/p3z26w2GyPfzQDnCorwFVYznoWtY7ixVoaV0SJ1Dkk6OJYL0f42nlNs5YlVA/HFKRvreXlQZbsZXilBOmao4NlZafq+GWlTSGgMgPxcAcj7DPjgLc2GUKUMImAkO7Amdyh2RkkMlW5+1sL3MbSY+3JCkKUru3KMEDUeqMY4rOKLeooauPJ13eG/+SN9h1HNQx34Kiapc99O5NyMpCaMKQTZGuhDdZ9NIX6YxIXSP/xAtXud4z8ktCcRtHmJ9kbNlwn4gSB6sfyGZWiksctE9rfGMLNTMgBug9Z/2SN9alwJGkBUl0jsE/6
  template:
    metadata:
      creationTimestamp: null
      name: arc-github-secret
      namespace: arc-runners
