# k8s/overlays/staging/postgres/kustomization.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/postgres
  - postgres-secret-sealedsecret.yml
namespace: staging
patchesStrategicMerge:
  - patch-affinity.yml
