apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        fsGroup: 70

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  template:
    spec:
      $patch: replace
      securityContext: {}
      containers:
        - name: postgres
          securityContext: {}