alertmanager:
  enabled: true
  alertmanagerSpec:
    secrets:
      - alertmanager-gmail
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
  config:
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'luisfernando198912@gmail.com'
      smtp_auth_username: 'luisfernando198912@gmail.com'
      smtp_auth_password_file: /etc/alertmanager/secrets/alertmanager-gmail/gmail-password
      smtp_require_tls: true
    route:
      group_by: ['namespace', 'alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'gmail'
      routes:
        - matchers:
            - alertname = "Watchdog"
          receiver: 'null'
        - matchers:
            - alertname = "InfoInhibitor"
          receiver: 'null'
        - matchers:
            - severity = "none"
          receiver: 'null'
        - matchers:
            - severity = "info"
          receiver: 'null'
          
    receivers:
      - name: 'null'
      - name: 'gmail'
        email_configs:
          - to: 'luisfernando198912@gmail.com'
            send_resolved: true
    inhibit_rules:
      - source_matchers:
          - severity = critical
        target_matchers:
          - severity =~ warning|info
        equal: ['namespace', 'alertname']
      - source_matchers:
          - severity = warning
        target_matchers:
          - severity = info
        equal: ['namespace', 'alertname']

grafana:
  enabled: true
  adminPassword: admin123
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: ALL
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki.monitoring.svc.cluster.local:3100
      access: proxy
      isDefault: false
      orgId: 1
      jsonData:
        maxLines: 1000
  plugins:
    - grafana-lokiexplore-app
  grafana.ini:
    feature_toggles:
      enable: lokiExploreLogsPanel

prometheus:
  prometheusSpec:
    retention: 24h
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    ruleSelector:
      matchLabels:
        release: kube-prom
    serviceMonitorSelector:
      matchLabels:
        release: kube-prom
    serviceMonitorNamespaceSelector: {}
    podMonitorNamespaceSelector: {}

prometheusOperator:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi