alertmanager:
  enabled: true
  alertmanagerSpec:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi

grafana:
  enabled: true
  adminPassword: admin123
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: ALL
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki.monitoring.svc.cluster.local:3100
      access: proxy
      isDefault: false
  plugins:
    - grafana-lokiexplore-app
  grafana.ini:
    feature_toggles:
      enable: lokiExploreLogsPanel    

prometheus:
  prometheusSpec:
    retention: 24h
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    ruleSelector:
      matchLabels:
        release: kube-prom
    serviceMonitorSelector:
      matchLabels:
        release: kube-prom
    serviceMonitorNamespaceSelector: {}
    podMonitorNamespaceSelector: {}

prometheusOperator:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi