apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wellness-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: wellness-ca
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"   
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "10"  # Disconnect if backend takes more than 10s to accept connection   
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"  # Disconnect if backend takes more than 30s to send a response    
    nginx.ingress.kubernetes.io/proxy-send-timeout: "30" # Disconnect if backend takes more than 30s to receive the request    
    nginx.ingress.kubernetes.io/limit-rps: "10" # Max 10 requests per second per IP — blocks brute force and scrapers   
    nginx.ingress.kubernetes.io/limit-connections: "5"  # Max 5 simultaneous connections per IP — prevents connection exhaustion
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - wellness.local
      secretName: wellness-tls
  rules:
    - host: wellness.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80