apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: wellness-bg
spec:
  type: ExternalName
  externalName: postgres.default.svc.cluster.local

  # This service acts as an alias for the Postgres service in the "default" namespace.
  # It allows applications in the "wellness-bg" namespace to access the database
  # using the name "postgres" without needing to know the exact service location in the cluster.
