---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-jwt-secret
  namespace: staging
spec:
  encryptedData:
    JWT_SECRET: AgATDNTCOUdR1aPbDqVaP4J1NlM8ATwzrBdtazLRHt6ygGv2JCFamr/no3u9cFEgscfzFxJhUgyTmS7PRonBbNPoQQXeSwhUkhJM+7jcOz1GaDf47hbmsjhDGymfQbfAbitl8jqELiPA6AIv3SRtCHvFYxrzMb8lN2igLTiDTuJu6l09s1gdw7XSDn4gN4XiSI7bopqyEqrRN0bX7FP4QcrNhUewySo3oB28bay+frjm41f7NDR145l49NPtMUGPqTKOH1brkw3fu6djH0zPPtng4vh5ezF3cbRXFe2dsOhrDhAXnFaUEI1OHcLQbJqFV/bHZv6wUUG251s3TIXoZrAjsutHCmOCnH/FH2hSnEQDaxM6kFjaO7xHD+W6B6oQ3+sgJ+Zbz0y5TjHedwcIu9GhHNWlprBPA0bplyQzbojWHWReRD3o68PxMVkT31DBRY1pmXIQn/7xGngTP7HaQuGQUSUs5GldSEgrMxubwd4Tw+3iay6vV//wL5p5ycng3VcIORTETzq7ZoPltMrOOl+iLgaApX2HElzNVPqTcYdarXYrTFUZYmI9Rlj11AXePb9TgwdQK8eiaTsYoXAsEERuKV8pNhTCYQBtDMQXVh/RxYovvmpvcZ+8uUsnRjf01j9YiM3mcmq9f7Ih93vWCoiFdX2wf5l4Mkp96XPy0XJ6vNQE2QoFge9xFZMjISR9tgqy8/IGoAlRgTdJrbYylnaiQtE=
  template:
    metadata:
      creationTimestamp: null
      name: backend-jwt-secret
      namespace: staging
