apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-prod
  namespace: argocd
spec:
  project: wellness
  source:
    repoURL: https://github.com/luisrodvilladaorg/wellness-gitops
    targetRevision: main
    path: k8s/overlays/prod/postgres
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
