apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runners
  namespace: argocd
spec:
  project: wellness
  source:
    repoURL: https://actions-runner-controller.github.io/actions-runner-controller
    chart: gha-runner-scale-set
    targetRevision: 0.10.1
    helm:
      values: |
        githubConfigUrl: https://github.com/luisrodvilladaorg
        githubConfigSecret: arc-github-secret
        minRunners: 1
        maxRunners: 5
        containerMode:
          type: kubernetes
          kubernetesModeWorkVolume:
            accessModes: ["ReadWriteOnce"]
            storageClassName: longhorn
            resources:
              requests:
                storage: 1Gi
        template:
          spec:
            containers:
              - name: runner
                image: ghcr.io/actions/actions-runner:latest
                resources:
                  requests:
                    cpu: 500m
                    memory: 512Mi
                  limits:
                    cpu: 1000m
                    memory: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-runners
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true