apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: wellness
  namespace: argocd
spec:
  description: wellness-ops project
  sourceRepos:
    - https://github.com/luisrodvilladaorg/wellness-gitops
    - https://prometheus-community.github.io/helm-charts
  destinations:
    - namespace: kube-system
      server: https://kubernetes.default.svc
    - namespace: default
      server: https://kubernetes.default.svc
    - namespace: staging
      server: https://kubernetes.default.svc
    - namespace: dev
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: "admissionregistration.k8s.io"
      kind: ValidatingWebhookConfiguration
    - group: "admissionregistration.k8s.io"
      kind: MutatingWebhookConfiguration  
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRole
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRoleBinding
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition