---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-tunnel-token
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    token: AgB4e5xPE1UJtMF7F2sbNxPUvuLXCFhXLEhqG+25PlzxYhf2VKZyc5sUQ3TR3+4R8xKm6Mvz5UdwH37KzUXKCF7ht/BWAtwMiUZ8wkjbIQTc1l2H4QjowAm1OtpxER49V/tSTyuj6mvX/Ic1ERDyaSjEWbud2Qa+dSPbPwNsp/Gkzt1amUAdlhH2+XtOILrOYdVK67us1hj8dJQjS2ERP1BA6aYLQxq8cW9qwR/L+CzrZXiImox0snDO0rHXE6cN+w1NUqfmW9N38xxZx8JnL6263zloOdlHToio62P3n+333X5+0eK/v5cfW/sgKJMDd5k1OeG5jx6omp4GRnI07kKNeGexx3ayQst1wKUs1xoeSLHPm9o8kFH5yGlJWbqIHLAdwv4lO8W3XgVjNeCRliRXaCtS+GZsEH+YRVfUDXHmVWPjHtJkyZdtm9jXpumxbaWMfZPTi+0eG5drxvvYvABEIaSyS2fKz449CpmEx7fwATAv3UX8E9ANXj5lc+oH6mYvTlitra09RcuzH3m81o0HsITOa1KmcGuZW1r0l6Eh2jkRTbydW8u20Gras+SYKRwm1YsxQMv3ahWQM5Xmv2zu6cCGgiuNDKnQC2eamPXF8REfCsYJ0S2Ht1DlhEOww2jshDdxIixtxZrPkMjXWXfLlv+daOIfR2GeVR+9xiHRRxbbxcbyMrOsWjSgQeQ5njmS8Mo1nUEjUqJw8qUFHE3sg1f2FfyaP9ReeEHVPyPNQ2IuBvoGQ+CezlY84eaY55Ekty8cKptTTnhhouxfpgM43ebjo1D7BTJPn4dX1/+3RCB5h053bq8F4zsCFoudPjZ6kqCkyUckGAJRyBCSljImttdaxbAMf0Oe6/cROvIBqEYlKooaa3N2aFx/JLfjRYvAFJ8Kce/Vgk0kcFT8FhMgG/yZzhrXSKM6xeHuTK8ZBGmTzuJC+7OB
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-tunnel-token
      namespace: cloudflare-tunnel
