---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgCXuGfBKL7CKJXFGK+YNojGDcrVl5muIYL1CdRPil/LX0fwKeQFp0bPaT6HBUUrpIaSyFjN1jNIs38bAYmAfrkA5DNqKtA45rfreKVXgB2b4c/w1Z12AeVIXrF1Gp3EEUzGPQzqhNRxFZ+dtH+rKne3LkLBQ1rYCeIojT8AUSo+cci6gFEOwKFw75I6UEvi3HZ87rN6y0z/EyXHAREbLgMwj7xi+zjX8D05xp3D2/UPa7WxQZx/tLStZqZ0dOLONkkDO/OMDbhfO1SrYE9opXQq7sDvzWgz1PzVbW8vH/xdbOJBFg/bxcnpVN2HLPXNRpLGjMcCBCGJZ/I3ERh3qtP/61/VRvooBQ9guWtvbD2dL5Z/YFKJzW9YAefxlFiCNa2IdxVVpDhHnh5BT6NiQtehaOQwJs9/h8gdqU/QfQvEd8TgGaH5VXWp6PAlW2JbcO318Ga6Zjr3jf8rbzQ/HI+hoVIPaXliY6Fr87FcIEY6Pd2jVqz4OpaBaZWzAVLSiunrPI0uje6zCeA8+sEqJR8bDr1up2kmQRBuhJAspljlSR7PdT++tdJkrP0DZw75J84VyRlHrhyg1PgCkJsSQdlbaVXqx0zbilv67QFarl7/0s5SA04mONfW/y5Ld7IAYU9hBpNQdiiWx3TJFqvc0YAFBHdIGu56QQ5tKbHNzu2g0ffHmWyBi++gWEJXAiuuiFzlZm2mgPT5bfC0HSDsTvkPlZsT/0c5SRoh2A2kkuGE93Drg02u7pKtVSXxmUVSOlXFpcwtRe3cDhsP20yWwfuIxQAROLiA8kvbU4yWXoVb12yMTuTxO5/WG/UEJKQILr48IDcktwXobe+QoZ7ITwEZ
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: velero
      name: cloud-credentials
      namespace: velero
    type: Opaque
