apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - cloud-credentials-sealedsecret.yml
  - backupstoragelocation.yml
  - schedules/backup-prod.yml
  - schedules/backup-staging.yml
  - schedules/backup-dev.yml
  - schedules/backup-argocd.yml
  - schedules/backup-monitoring.yml
